export const FN='dpro-housekeep-product-ready-v2';
export const COMPANY='dpro_housekeep_demo';
export const DBV='HOUSEKEEP-DB-PR2-20260824';
export const ADAPTER='HOUSEKEEP-PR2-GATEWAY-20260824';
export const FRONT='HOUSEKEEP-8-PR2-FRONTEND-20260824';
export const WORKER='HOUSEKEEP-8-PR2-GATEWAY-20260824';
export const LEGACY='https://dpro-housekeep-line-api.dpromstk2000.workers.dev';
const SB=Deno.env.get('SUPABASE_URL')||'';
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const ORIGINS=new Set(['https://dpromstk2000-lab.github.io','https://dpro-shop.com','https://www.dpro-shop.com']);
export function cors(req){const o=req.headers.get('origin')||'';const h={'vary':'Origin','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-admin-key,x-staff-session,x-line-id-token,authorization','x-dpro-adapter-version':ADAPTER,'cache-control':'no-store'};if(ORIGINS.has(o))h['access-control-allow-origin']=o;return h}
export function originAllowed(req){const o=req.headers.get('origin');return !o||ORIGINS.has(o)}
export function out(req,d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8',...cors(req)}})}
export function pathOf(req){const p=new URL(req.url).pathname,m='/'+FN,i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||'/'):p}
export async function db(path,init={}){const h=new Headers(init.headers||{});h.set('apikey',KEY);h.set('authorization',`Bearer ${KEY}`);h.set('accept','application/json');if(init.body&&!h.has('content-type'))h.set('content-type','application/json');const r=await fetch(`${SB}/rest/v1/${path}`,{...init,headers:h});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Object.assign(new Error('DB_'+r.status),{status:500,details:d});return d}
export async function one(path){const x=await db(path);return Array.isArray(x)?x[0]||null:x}
export async function company(code){const c=await one(`housekeep_companies?company_code=eq.${encodeURIComponent(code)}&select=*`);if(!c||c.is_active===false)throw Object.assign(new Error('事業者が見つかりません'),{status:404});return c}
export async function versionRow(){return one('housekeep_product_versions?product_code=eq.HOUSEKEEP&select=*')}
export async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function b64bytes(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
export async function pbk(code,salt,iter){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(code),{name:'PBKDF2'},false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:b64bytes(salt),iterations:+iter,hash:'SHA-256'},k,256);let x='';for(const v of new Uint8Array(b))x+=String.fromCharCode(v);return btoa(x)}
export function safeEq(a,b){if(!a||!b||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
export function phone(v){let s=String(v||'').normalize('NFKC').replace(/[^0-9+]/g,'');if(s.startsWith('+81'))s='0'+s.slice(3);if(s.startsWith('0081'))s='0'+s.slice(4);return s.replace(/\D/g,'')}
export function guardDate(date,time,c){if(!/^\d{4}-\d{2}-\d{2}$/.test(date||'')||!/^\d{2}:\d{2}/.test(time||''))throw Object.assign(new Error('希望日時を確認してください。'),{status:400});const [,m]=time.slice(0,5).split(':').map(Number);if(m%30!==0)throw Object.assign(new Error('希望時間は30分単位で指定してください。'),{status:400});const d=new Date(`${date}T${time.slice(0,5)}:00+09:00`);if(!Number.isFinite(d.getTime())||d.getTime()<=Date.now())throw Object.assign(new Error('過去日時は予約できません。'),{status:400});if(d.getTime()<Date.now()+Number(c.minimum_lead_hours||0)*3600000)throw Object.assign(new Error('予約リードタイムを満たしていません。'),{status:400})}
export async function proxy(req,u,p,opt={}){const t=new URL(LEGACY+p);for(const [k,v] of u.searchParams)t.searchParams.append(k,v);const h=new Headers(req.headers);h.delete('host');h.delete('origin');h.delete('x-staff-session');h.delete('x-line-id-token');if(opt.demo){t.searchParams.set('admin_key','1234');h.set('x-admin-key','1234')}let body=opt.body;if(body===undefined&&!['GET','HEAD'].includes(req.method))body=req.body;if(body instanceof FormData)h.delete('content-type');const r=await fetch(t,{method:req.method,headers:h,body});const hh=cors(req),ct=r.headers.get('content-type');return new Response(r.body,{status:r.status,headers:{...(ct?{'content-type':ct}:{}),...hh}})}
export async function lineVerify(req,c,raw){const b=await one(`housekeep_line_bindings?company_code=eq.${encodeURIComponent(c.company_code)}&select=*`);if(!b||b.binding_status!=='bound'||!b.channel_id)throw Object.assign(new Error('LINE本人確認bindingは契約時設定待ちです。'),{status:503});const tok=(req.headers.get('x-line-id-token')||'').trim();if(!tok)throw Object.assign(new Error('LINE ID Tokenが必要です'),{status:401});const r=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:tok,client_id:String(b.channel_id)})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.sub||String(d.aud)!==String(b.channel_id)||Number(d.exp||0)*1000<=Date.now()||(raw&&String(raw)!==String(d.sub)))throw Object.assign(new Error('LINE ID Tokenのsub/aud/exp検証に失敗しました'),{status:401});return String(d.sub)}
export async function availability(req,u,c){const date=u.searchParams.get('date')||'';const ex=await one(`housekeep_calendar_exceptions?company_code=eq.${encodeURIComponent(c.company_code)}&target_date=eq.${encodeURIComponent(date)}&select=*`);if(ex?.exception_type==='temporary_closed')return out(req,{ok:true,date,closed:true,reason:'temporary_closed',slots:[]});if(ex?.exception_type==='special_open'){const a=[],[sh,sm]=String(ex.open_time).slice(0,5).split(':').map(Number),[eh,em]=String(ex.close_time).slice(0,5).split(':').map(Number);for(let m=sh*60+sm;m<eh*60+em;m+=30)a.push({time:`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,available:true});return out(req,{ok:true,date,closed:false,reason:'special_open',slots:a})}return proxy(req,u,'/api/public/availability')}
export async function ready(c){const v=await versionRow(),b=await one(`housekeep_line_bindings?company_code=eq.${encodeURIComponent(c.company_code)}&select=binding_status,channel_id`),aligned=!!v&&v.db_version===DBV&&v.adapter_version===ADAPTER&&v.frontend_version===FRONT&&v.worker_version===WORKER;return {ok:aligned,product:'HOUSEKEEP',versionsAligned:aligned,versions:{db:v?.db_version,adapter:v?.adapter_version,frontend:v?.frontend_version,worker:v?.worker_version},security:{productionGuard:c.production_guard===true,demoCodeProductionRejected:true,line:{checks:['sub','aud','exp'],bindingStatus:b?.binding_status||'missing',clientSuppliedIdentityAccepted:false,productionUnboundFailsClosed:true},staff:{serverIssuedSession:true,capabilityEnforced:true,revokeSupported:true,criticalAudit:true,clientStaffIdAuthoritative:false},owner:{hash:'PBKDF2-SHA256',productionMissingCredentialFailsClosed:true},cors:{wildcard:false},photo:{bucket:'housekeep-job-photos',expectedPublic:false,customerVisibleDefault:false}},feature_bindings:{support_recovery:false,website_sync:false,service_binding:false,integration_status:'deferred_until_contract'},checked_at:new Date().toISOString()}}
