import {db,one,sha,pbk,safeEq} from './core.ts';
export function adminKey(req,u){return (req.headers.get('x-admin-key')||u.searchParams.get('admin_key')||'').trim()}
export async function owner(req,u,c){const code=adminKey(req,u);if(!code)throw Object.assign(new Error('管理コードを入力してください。'),{status:401});const cr=await one(`housekeep_owner_credentials?company_code=eq.${encodeURIComponent(c.company_code)}&select=*`);if(!cr||!cr.is_active)throw Object.assign(new Error('本番Owner認証が未設定です。'),{status:401});if(c.is_demo){if(!c.production_guard||!cr.is_demo_only||code!=='1234')throw Object.assign(new Error('管理コードが正しくありません'),{status:401})}else if(cr.is_demo_only||code==='1234')throw Object.assign(new Error('デモ管理コードは本番では使用できません。'),{status:401});if(!safeEq(await pbk(code,cr.salt_b64,cr.iterations),cr.hash_b64))throw Object.assign(new Error('管理コードが正しくありません'),{status:401});return true}
function caps(role){const a=['jobs_read','job_detail','status_update','checklist_update','note_update','photo_upload'];if(role==='owner'||role==='manager')a.push('customer_visible_photo');return a}
async function log(c,actor,aid,action,target=null,details={}){try{await db('housekeep_activity_logs',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({company_code:c,actor_type:actor,actor_id:aid||null,action,target_type:'booking',target_id:target||null,details})})}catch(e){console.error('audit',e.message)}}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);let s='';for(const b of a)s+=String.fromCharCode(b);return 'hkst_'+btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export async function issueStaff(req,u,c){await owner(req,u,c);const b=await req.json().catch(()=>({})),id=String(b.staff_id||'');const st=await one(`housekeep_staff?id=eq.${encodeURIComponent(id)}&company_code=eq.${encodeURIComponent(c.company_code)}&is_active=eq.true&select=id,staff_code,name,role`);if(!st)throw Object.assign(new Error('スタッフが見つかりません'),{status:404});const t=token(),h=await sha(t),cp=caps(st.role),exp=new Date(Date.now()+8*3600000).toISOString();const ins=await db('housekeep_staff_sessions',{method:'POST',headers:{'Prefer':'return=representation'},body:JSON.stringify({company_code:c.company_code,staff_id:st.id,token_hash:h,capabilities:cp,issued_by:'owner',expires_at:exp})});await log(c.company_code,'owner',null,'staff_session_issued',st.id,{session_id:ins?.[0]?.id});return {ok:true,session_token:t,expires_at:exp,staff:st,capabilities:cp,server_authority:true}}
export async function staffSession(req,c){const t=(req.headers.get('x-staff-session')||'').trim();if(!t)throw Object.assign(new Error('スタッフセッションが必要です'),{status:401});const h=await sha(t),s=await one(`housekeep_staff_sessions?token_hash=eq.${h}&company_code=eq.${encodeURIComponent(c.company_code)}&select=*`);if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw Object.assign(new Error('スタッフセッションが無効です'),{status:401});const st=await one(`housekeep_staff?id=eq.${encodeURIComponent(s.staff_id)}&company_code=eq.${encodeURIComponent(c.company_code)}&is_active=eq.true&select=id,staff_code,name,role`);if(!st)throw Object.assign(new Error('スタッフが無効です'),{status:401});return {s,st,cap:Array.isArray(s.capabilities)?s.capabilities:[]}}
export async function revokeStaff(req,c){const a=await staffSession(req,c);await db(`housekeep_staff_sessions?id=eq.${a.s.id}`,{method:'PATCH',body:JSON.stringify({revoked_at:new Date().toISOString(),revoke_reason:'self_revoke'})});await log(c.company_code,'staff_session',a.st.id,'staff_session_revoked',a.st.id,{session_id:a.s.id});return {ok:true,revoked:true}}
export async function auditStaff(c,a,p,method,target){await log(c.company_code,'staff_session',a.st.id,'staff_'+p.split('/').pop()+'_'+method.toLowerCase(),target||null,{session_id:a.s.id})}
