import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {COMPANY,DBV,ADAPTER,FRONT,WORKER,cors,out,pathOf,originAllowed,company,phone,guardDate,proxy,lineVerify,availability,ready,db} from './core.ts';
import {owner,issueStaff,staffSession,revokeStaff,auditStaff} from './auth.ts';
Deno.serve(async req=>{const u=new URL(req.url),p=pathOf(req);try{
 if(req.method==='OPTIONS')return new Response(null,{status:originAllowed(req)?204:403,headers:cors(req)});
 if(!originAllowed(req))return out(req,{ok:false,error:'許可されていないOriginです'},403);
 const c=await company(u.searchParams.get('company_code')||COMPANY);
 if(p==='/'||p==='/api/health'){const x=await ready(c);return out(req,{ok:true,version:WORKER,supabase:'ok',database_version:DBV,frontend_version:FRONT,adapter_version:ADAPTER,versionsAligned:x.versionsAligned})}
 if(p==='/api/product-ready/check')return out(req,await ready(c));
 if(p==='/api/line/capability')return out(req,{ok:true,verification:'LINE_ID_TOKEN_/oauth2/v2.1/verify',checks:['sub','aud','exp'],clientSuppliedIdentityAccepted:false,productionUnboundFailsClosed:true});
 if(p==='/api/owner/capability')return out(req,{ok:true,serverAuthority:true,hash:'PBKDF2-SHA256',demoCodeProductionRejected:true,productionMissingCredentialFailsClosed:true});
 if(p==='/api/staff/capability'&&!req.headers.get('x-staff-session'))return out(req,{ok:true,serverIssuedSession:true,permissionEnforced:true,revokeSupported:true,criticalAudit:true,clientStaffIdAuthoritative:false});
 if(p==='/api/staff/session'&&req.method==='POST')return out(req,await issueStaff(req,u,c));
 if(p==='/api/staff/session/revoke'&&req.method==='POST')return out(req,await revokeStaff(req,c));
 if(p==='/api/staff/capability'){const a=await staffSession(req,c);return out(req,{ok:true,staff:a.st,capabilities:a.cap,serverAuthority:true})}
 if(p==='/api/admin/phone-normalize-check'){await owner(req,u,c);const xs=['090-1111-2222','０９０１１１１２２２２','+81 90 1111 2222','0081-90-1111-2222'];return out(req,{ok:true,normalized:xs.map(input=>({input,output:phone(input)}))})}
 if(p==='/api/admin/system-check'){await owner(req,u,c);const x=await ready(c),items=[{key:'gateway',label:'HOUSEKEEP専用Gateway',ok:true,detail:ADAPTER},{key:'version',label:'Version整合',ok:x.versionsAligned,detail:`${DBV} / ${FRONT}`},{key:'phone',label:'電話番号正規化',ok:phone('+81 90 1111 2222')==='09011112222',detail:'fullwidth/+81/0081'},{key:'production_guard',label:'Production Guard',ok:c.production_guard===true,detail:`demo=${c.is_demo}`},{key:'line',label:'LINE Fail-close',ok:true,detail:'sub/aud/exp + unbound fail-close'},{key:'staff',label:'Staff server authority',ok:true,detail:'session/capability/revoke/audit'}];return out(req,{ok:true,all_ok:items.every(x=>x.ok),passed:items.filter(x=>x.ok).length,total:items.length,version:WORKER,items})}
 if(p==='/api/public/availability')return availability(req,u,c);
 if(p==='/api/booking/create'&&req.method==='POST'){const b=await req.json().catch(()=>null);if(!b)throw Object.assign(new Error('JSON bodyが必要です'),{status:400});guardDate(b.requested_date,b.requested_start_time,c);if(b?.customer?.line_user_id)b.customer.line_user_id=await lineVerify(req,c,b.customer.line_user_id);return proxy(req,u,p,{body:JSON.stringify(b)})}
 if((p==='/api/customer/lookup'||p==='/api/booking/lookup')&&(u.searchParams.get('line_user_id')||u.searchParams.get('uid'))){const raw=u.searchParams.get('line_user_id')||u.searchParams.get('uid');const sub=await lineVerify(req,c,raw);u.searchParams.delete('uid');u.searchParams.set('line_user_id',sub);return proxy(req,u,p)}
 if(p==='/api/customer/lookup'||p==='/api/booking/lookup')return proxy(req,u,p);
 if(p.startsWith('/api/staff/')){const a=await staffSession(req,c),need=p.endsWith('/jobs')||p.endsWith('/job')?'jobs_read':p.endsWith('/status')?'status_update':p.includes('/check')?'checklist_update':p.endsWith('/note')?'note_update':p.endsWith('/photo')?'photo_upload':'jobs_read';if(!a.cap.includes(need))throw Object.assign(new Error('このスタッフ権限では操作できません'),{status:403});const q=u.searchParams.get('staff_id');if(q&&q!==a.st.id)throw Object.assign(new Error('client staff_id is not authoritative'),{status:403});u.searchParams.set('staff_id',a.st.id);if(!c.is_demo)throw Object.assign(new Error('本番staff service bindingは契約時設定待ちです。'),{status:503});let body,target=null;const ct=req.headers.get('content-type')||'';if(!['GET','HEAD'].includes(req.method)&&ct.includes('application/json')){const b=await req.json().catch(()=>({}));if(b.staff_id&&String(b.staff_id)!==a.st.id)throw Object.assign(new Error('client staff_id is not authoritative'),{status:403});b.staff_id=a.st.id;target=b.booking_id||b.check_id||null;body=JSON.stringify(b)}else if(!['GET','HEAD'].includes(req.method)&&ct.includes('multipart/form-data')){const f=await req.formData(),sent=String(f.get('staff_id')||'');if(sent&&sent!==a.st.id)throw Object.assign(new Error('client staff_id is not authoritative'),{status:403});if(String(f.get('customer_visible')||'false')==='true'&&!a.cap.includes('customer_visible_photo'))throw Object.assign(new Error('顧客公開写真の権限がありません'),{status:403});f.set('staff_id',a.st.id);target=String(f.get('booking_id')||'')||null;body=f}if(!['GET','HEAD'].includes(req.method))await auditStaff(c,a,p,req.method,target);return proxy(req,u,p,{demo:true,body})}
 if(p==='/api/admin/demo-prepare'&&req.method==='POST'){await owner(req,u,c);if(!c.is_demo||c.production_guard!==true)throw Object.assign(new Error('DEMO PREPAREは保護されたデモ環境だけで実行できます'),{status:403});const r=await proxy(req,u,p,{demo:true});await db('housekeep_demo_runs',{method:'POST',headers:{'Prefer':'return=minimal'},body:JSON.stringify({company_code:c.company_code,action:'demo_prepare',result:r.ok?'PASS':'FAIL',requested_by:'owner',details:{gateway:'HOUSEKEEP-PR2-GATEWAY-20260824',status:r.status}})});return r}
 if(p.startsWith('/api/admin/')){await owner(req,u,c);if(!c.is_demo)throw Object.assign(new Error('本番service bindingは契約時設定待ちです。'),{status:503});return proxy(req,u,p,{demo:true})}
 if(p.startsWith('/api/public/')||p==='/api/inquiry/create')return proxy(req,u,p);
 return out(req,{ok:false,error:'Endpoint not found'},404)
 }catch(e){console.error(p,e);return out(req,{ok:false,error:e.message||'Internal error',details:e.details||undefined},Number(e.status||500))}});
